from pydantic import BaseModel, Field
from typing import Literal
from .medication import MedicationCommand


class ClinicalAction(BaseModel):
    """
    Represents a single, specific medical intervention recommended by the AI triage engine.
    """
    action_category: Literal[
        "Airway", 
        "Breathing", 
        "Circulation/Hemorrhage", 
        "Medication", 
        "Exposure/Environment", 
        "Transport/Evacuation"
    ] = Field(
        ...,
        description="The primary ABCDE category of the intervention."
    )
    
    intervention: str = Field(
        ...,
        description="Clear, actionable command for the medical provider (e.g., 'Perform needle decompression', 'Administer 500cc Normal Saline')."
    )
    
    urgency: Literal["Immediate", "High", "Routine"] = Field(
        ...,
        description="The operational urgency of this specific action."
    )
    
    clinical_rationale: str = Field(
        ...,
        description="A concise justification for this action directly referencing the patient's vitals, symptoms, or scene context."
    )
class ClinicalAssessment(BaseModel):
    """
    "Represents the final structured output generated by the AI triage engine, including triage level, primary threats, and prioritized actionable interventions."  
    """
    triage_level: Literal["Red", "Yellow", "Green", "Black"] = Field(
        ..., description="The triage level assigned to the patient based on their clinical assessment."
    )

    main_threat: str = Field(
        ..., description="The primary life-threatening condition identified in the patient (e.g., 'Tension Pneumothorax', 'Massive Hemorrhage', 'Airway Obstruction')."
    )

    recommended_actions: list[ClinicalAction] = Field(
        ..., description="A list of specific, prioritized clinical actions recommended for this patient based on their assessment."
    )

    critical_warnings: list[str] = Field(
        default_factory=list, description="Any critical warnings or contraindications that the provider must be aware of when treating this patient (e.g., 'Do not administer Fentanyl due to suspected head injury', 'Avoid IV fluids in suspected CHF')."
    )
    confidence_score: int = Field(
        ..., ge=0, le=100, description="The AI's confidence in the accuracy of this assessment, expressed as a percentage. This can be used to determine if a reassessment or human review is needed."
    )
